<?php

/**
 * Get the path to an asset, for inclusion in HTML
 * @return string
 */
function asset_path( $asset_name, $production = false ) {
	$asset_directory = $production ? "dist" : "assets";
	$asset_filename = find_asset( $asset_name, $production );
	return get_stylesheet_directory_uri() . "/${asset_directory}/${asset_filename}";
}

/**
 * Look up an asset's fingerprinted filename from the manifest (if available)
 *
 * The manifest is generated by `gulp build`.
 *
 * If no manifest is found, returns the filename.
 *
 * @return string
 */
function find_asset( $asset_name, $fingerprint = false ) {
	$mapping_json = file_get_contents(dirname(__FILE__) . "/assets.json");

	if( $mapping_json && $fingerprint ) {
		$mapping = json_decode($mapping_json,true);
		if( isset( $mapping[$asset_name] ) ) {
			return $mapping[$asset_name];
		}
	}

	return $asset_name;
}
